// This file is auto-generated by @hey-api/openapi-ts

export const ContractSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      minimum: -2147483648,
      maximum: 2147483647,
    },
    title: {
      type: 'string',
    },
    description: {
      type: 'string',
      nullable: true,
    },
    endDate: {
      type: 'string',
      nullable: true,
    },
    status: {
      type: 'string',
      enum: [
        'Draft',
        'Legal Review',
        'Management Review',
        'Accepted',
        'Rejected',
        'Rejected Legal',
        'Canceled',
      ],
    },
    riskScore: {
      type: 'integer',
      nullable: true,
      minimum: -2147483648,
      maximum: 2147483647,
    },
    reason: {
      type: 'string',
      nullable: true,
    },
    createdBy: {
      type: 'string',
      nullable: true,
    },
    updatedBy: {
      type: 'string',
      nullable: true,
    },
    deleted: {
      type: 'boolean',
    },
    urlContract: {
      type: 'string',
      nullable: true,
    },
    createdAt: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'string',
          format: 'date',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'string',
          format: 'date',
        },
      ],
    },
  },
  required: [
    'id',
    'title',
    'description',
    'endDate',
    'status',
    'riskScore',
    'reason',
    'createdBy',
    'updatedBy',
    'deleted',
    'urlContract',
    'createdAt',
    'updatedAt',
  ],
} as const;

export const ContractWithRelationsSchema = {
  allOf: [
    {
      $ref: '#/components/schemas/Contract',
    },
    {
      type: 'object',
      properties: {
        versions: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'number',
              },
              filePath: {
                type: 'string',
              },
              versionNo: {
                type: 'number',
              },
              uploadedAt: {
                type: 'string',
                format: 'date-time',
              },
            },
            required: ['id', 'filePath', 'versionNo', 'uploadedAt'],
          },
        },
        parties: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'number',
              },
              partyName: {
                type: 'string',
              },
              partyRole: {
                type: 'string',
              },
            },
            required: ['id', 'partyName', 'partyRole'],
          },
        },
        clauses: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'number',
              },
              clauseText: {
                type: 'string',
              },
              clauseDescription: {
                type: 'string',
                nullable: true,
              },
              riskLevel: {
                type: 'string',
                nullable: true,
              },
            },
            required: ['id', 'clauseText', 'clauseDescription', 'riskLevel'],
          },
        },
      },
    },
  ],
} as const;

export const AlertSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      minimum: -2147483648,
      maximum: 2147483647,
    },
    contractId: {
      type: 'integer',
      minimum: -2147483648,
      maximum: 2147483647,
    },
    message: {
      type: 'string',
    },
    priority: {
      type: 'string',
      enum: ['low', 'medium', 'high', 'critical'],
    },
    isRead: {
      type: 'boolean',
    },
    createdBy: {
      type: 'string',
      nullable: true,
    },
    createdAt: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'string',
          format: 'date',
        },
      ],
    },
  },
  required: [
    'id',
    'contractId',
    'message',
    'priority',
    'isRead',
    'createdBy',
    'createdAt',
  ],
} as const;

export const AlertWithContractSchema = {
  allOf: [
    {
      $ref: '#/components/schemas/Alert',
    },
    {
      type: 'object',
      properties: {
        contract: {
          type: 'object',
          properties: {
            id: {
              type: 'number',
            },
            title: {
              type: 'string',
            },
            status: {
              type: 'string',
            },
          },
          required: ['id', 'title', 'status'],
        },
      },
    },
  ],
} as const;
