// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import {
  getContractByIdResponseTransformer,
  healthResponseTransformer,
  protectedhealthResponseTransformer,
} from './transformers.gen';
import type {
  AcceptContractData,
  AcceptContractErrors,
  AcceptContractResponses,
  CreateClauseData,
  CreateClauseErrors,
  CreateClauseResponses,
  CreateContractData,
  CreateContractErrors,
  CreateContractResponses,
  DeleteContractData,
  DeleteContractErrors,
  DeleteContractResponses,
  GetAlertByIdData,
  GetAlertByIdErrors,
  GetAlertByIdResponses,
  GetAlertsData,
  GetAlertsResponses,
  GetContractByIdData,
  GetContractByIdErrors,
  GetContractByIdResponses,
  GetContractsData,
  GetContractsResponses,
  GetUnreadAlertsCountData,
  GetUnreadAlertsCountErrors,
  GetUnreadAlertsCountResponses,
  HealthData,
  HealthResponses,
  MarkAlertAsReadData,
  MarkAlertAsReadErrors,
  MarkAlertAsReadResponses,
  ProtectedhealthData,
  ProtectedhealthResponses,
  RejectContractData,
  RejectContractErrors,
  RejectContractResponses,
  UpdateContractData,
  UpdateContractErrors,
  UpdateContractResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const health = <ThrowOnError extends boolean = false>(
  options?: Options<HealthData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    HealthResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: healthResponseTransformer,
    responseType: 'json',
    url: '/api/health',
    ...options,
  });
};

export const protectedhealth = <ThrowOnError extends boolean = false>(
  options?: Options<ProtectedhealthData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ProtectedhealthResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: protectedhealthResponseTransformer,
    responseType: 'json',
    url: '/api/health/protected',
    ...options,
  });
};

export const getContracts = <ThrowOnError extends boolean = false>(
  options?: Options<GetContractsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetContractsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/contracts',
    ...options,
  });
};

export const createContract = <ThrowOnError extends boolean = false>(
  options?: Options<CreateContractData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateContractResponses,
    CreateContractErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/contracts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const deleteContract = <ThrowOnError extends boolean = false>(
  options: Options<DeleteContractData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteContractResponses,
    DeleteContractErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/contracts/{id}',
    ...options,
  });
};

export const getContractById = <ThrowOnError extends boolean = false>(
  options: Options<GetContractByIdData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    GetContractByIdResponses,
    GetContractByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getContractByIdResponseTransformer,
    responseType: 'json',
    url: '/api/contracts/{id}',
    ...options,
  });
};

export const updateContract = <ThrowOnError extends boolean = false>(
  options: Options<UpdateContractData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    UpdateContractResponses,
    UpdateContractErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/contracts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const createClause = <ThrowOnError extends boolean = false>(
  options: Options<CreateClauseData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateClauseResponses,
    CreateClauseErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/contracts/{id}/clause',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const rejectContract = <ThrowOnError extends boolean = false>(
  options: Options<RejectContractData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    RejectContractResponses,
    RejectContractErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/contracts/{id}/reject',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const acceptContract = <ThrowOnError extends boolean = false>(
  options: Options<AcceptContractData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    AcceptContractResponses,
    AcceptContractErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/contracts/{id}/accept',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const getAlerts = <ThrowOnError extends boolean = false>(
  options?: Options<GetAlertsData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetAlertsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/alerts',
    ...options,
  });
};

export const getAlertById = <ThrowOnError extends boolean = false>(
  options: Options<GetAlertByIdData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    GetAlertByIdResponses,
    GetAlertByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/alerts/{id}',
    ...options,
  });
};

export const markAlertAsRead = <ThrowOnError extends boolean = false>(
  options: Options<MarkAlertAsReadData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    MarkAlertAsReadResponses,
    MarkAlertAsReadErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/alerts/{id}/read',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const getUnreadAlertsCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetUnreadAlertsCountData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetUnreadAlertsCountResponses,
    GetUnreadAlertsCountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/alerts/unread/count',
    ...options,
  });
};
