// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://localhost:5001' | (string & {});
};

export type Contract = {
  id: number;
  title: string;
  description: string;
  endDate: string;
  status:
    | 'Draft'
    | 'Legal Review'
    | 'Management Review'
    | 'Accepted'
    | 'Rejected'
    | 'Rejected Legal'
    | 'Canceled';
  riskScore: number;
  reason: string;
  createdBy: string;
  updatedBy: string;
  deleted: boolean;
  urlContract: string;
  createdAt: string;
  updatedAt: string;
};

export type ContractWithRelations = Contract & {
  versions?: Array<{
    id: number;
    filePath: string;
    versionNo: number;
    uploadedAt: Date;
  }>;
  parties?: Array<{
    id: number;
    partyName: string;
    partyRole: string;
  }>;
  clauses?: Array<{
    id: number;
    clauseText: string;
    clauseDescription: string;
    riskLevel: string;
  }>;
};

export type Alert = {
  id: number;
  contractId: number;
  message: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  isRead: boolean;
  createdBy: string;
  createdAt: string;
};

export type AlertWithContract = Alert & {
  contract?: {
    id: number;
    title: string;
    status: string;
  };
};

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health';
};

export type HealthResponses = {
  /**
   * Health check successful
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: {
      status?: string;
      timestamp: Date;
    };
  };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ProtectedhealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health/protected';
};

export type ProtectedhealthResponses = {
  /**
   * Protected Health check successful
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: {
      status?: string;
      user?: {
        id: string;
        email: string;
        emailVerified: boolean;
        name: string;
        role: 'internal' | 'legal' | 'management';
        createdAt: Date;
        updatedAt: Date;
        image?: string;
      };
      session?: {
        id: string;
        userId: string;
        expiresAt: Date;
        createdAt: Date;
        updatedAt: Date;
        token: string;
        ipAddress?: string;
        userAgent?: string;
      };
      timestamp: Date;
    };
  };
};

export type ProtectedhealthResponse =
  ProtectedhealthResponses[keyof ProtectedhealthResponses];

export type GetContractsData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    limit?: string;
    status?:
      | 'Draft'
      | 'Legal Review'
      | 'Management Review'
      | 'Accepted'
      | 'Rejected'
      | 'Rejected Legal'
      | 'Canceled';
    search?: string;
  };
  url: '/api/contracts';
};

export type GetContractsResponses = {
  /**
   * List of contracts retrieved successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: {
      contracts: Array<Contract>;
      pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
      };
    };
  };
};

export type GetContractsResponse =
  GetContractsResponses[keyof GetContractsResponses];

export type CreateContractData = {
  body?: {
    title: string;
    description?: string;
    endDate?: string;
    status?:
      | 'Draft'
      | 'Legal Review'
      | 'Management Review'
      | 'Accepted'
      | 'Rejected'
      | 'Rejected Legal'
      | 'Canceled';
    party: Array<{
      partyName: string;
      partyRole: string;
    }>;
  };
  path?: never;
  query?: never;
  url: '/api/contracts';
};

export type CreateContractErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type CreateContractError =
  CreateContractErrors[keyof CreateContractErrors];

export type CreateContractResponses = {
  /**
   * Contract created successfully
   */
  201: {
    success: boolean;
    message: string;
    code?: number;
    data?: Contract & {
      presignedUrl: string;
    };
  };
};

export type CreateContractResponse =
  CreateContractResponses[keyof CreateContractResponses];

export type DeleteContractData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/contracts/{id}';
};

export type DeleteContractErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type DeleteContractError =
  DeleteContractErrors[keyof DeleteContractErrors];

export type DeleteContractResponses = {
  /**
   * Contract deleted successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: Contract & {
      presignedUrl: string;
    };
  };
};

export type DeleteContractResponse =
  DeleteContractResponses[keyof DeleteContractResponses];

export type GetContractByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    includeRelations?: string;
  };
  url: '/api/contracts/{id}';
};

export type GetContractByIdErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type GetContractByIdError =
  GetContractByIdErrors[keyof GetContractByIdErrors];

export type GetContractByIdResponses = {
  /**
   * Contract retrieved successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: ContractWithRelations;
  };
};

export type GetContractByIdResponse =
  GetContractByIdResponses[keyof GetContractByIdResponses];

export type UpdateContractData = {
  body?: {
    title?: string;
    description?: string;
    endDate?: string;
    status?:
      | 'Draft'
      | 'Legal Review'
      | 'Management Review'
      | 'Accepted'
      | 'Rejected'
      | 'Rejected Legal'
      | 'Canceled';
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/contracts/{id}';
};

export type UpdateContractErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type UpdateContractError =
  UpdateContractErrors[keyof UpdateContractErrors];

export type UpdateContractResponses = {
  /**
   * Contract updated successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: Contract & {
      presignedUrl: string;
    };
  };
};

export type UpdateContractResponse =
  UpdateContractResponses[keyof UpdateContractResponses];

export type CreateClauseData = {
  body?: Array<{
    clauseText: string;
    clauseDescription?: string;
  }>;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/contracts/{id}/clause';
};

export type CreateClauseErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type CreateClauseError = CreateClauseErrors[keyof CreateClauseErrors];

export type CreateClauseResponses = {
  /**
   * Clause created successfully
   */
  201: {
    success: boolean;
    message: string;
    code?: number;
    data?: Array<{
      id: number;
      contractId: number;
      clauseText: string;
      clauseDescription: string;
      createdBy: string;
      updatedBy: string;
      createdAt: string;
      updatedAt: string;
    }>;
  };
};

export type CreateClauseResponse =
  CreateClauseResponses[keyof CreateClauseResponses];

export type RejectContractData = {
  body?: {
    rejectType: 'legal' | 'all';
    reason: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/contracts/{id}/reject';
};

export type RejectContractErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type RejectContractError =
  RejectContractErrors[keyof RejectContractErrors];

export type RejectContractResponses = {
  /**
   * Contract rejected successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: Contract & {
      presignedUrl: string;
    };
  };
};

export type RejectContractResponse =
  RejectContractResponses[keyof RejectContractResponses];

export type AcceptContractData = {
  body?: {
    reason: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/contracts/{id}/accept';
};

export type AcceptContractErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type AcceptContractError =
  AcceptContractErrors[keyof AcceptContractErrors];

export type AcceptContractResponses = {
  /**
   * Contract accepted successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: Contract & {
      presignedUrl: string;
    };
  };
};

export type AcceptContractResponse =
  AcceptContractResponses[keyof AcceptContractResponses];

export type GetAlertsData = {
  body?: never;
  path?: never;
  query?: {
    page?: string;
    limit?: string;
    priority?: 'low' | 'medium' | 'high' | 'critical';
    isRead?: string;
    contractId?: string;
  };
  url: '/api/alerts';
};

export type GetAlertsResponses = {
  /**
   * List of alerts retrieved successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: {
      alerts: Array<AlertWithContract>;
      pagination: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
      };
    };
  };
};

export type GetAlertsResponse = GetAlertsResponses[keyof GetAlertsResponses];

export type GetAlertByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/alerts/{id}';
};

export type GetAlertByIdErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type GetAlertByIdError = GetAlertByIdErrors[keyof GetAlertByIdErrors];

export type GetAlertByIdResponses = {
  /**
   * Alert retrieved successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: AlertWithContract;
  };
};

export type GetAlertByIdResponse =
  GetAlertByIdResponses[keyof GetAlertByIdResponses];

export type MarkAlertAsReadData = {
  body?: {
    isRead: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/api/alerts/{id}/read';
};

export type MarkAlertAsReadErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type MarkAlertAsReadError =
  MarkAlertAsReadErrors[keyof MarkAlertAsReadErrors];

export type MarkAlertAsReadResponses = {
  /**
   * Alert marked as read successfully
   */
  200: {
    success: boolean;
    message: string;
    code?: number;
    data?: AlertWithContract;
  };
};

export type MarkAlertAsReadResponse =
  MarkAlertAsReadResponses[keyof MarkAlertAsReadResponses];

export type GetUnreadAlertsCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/alerts/unread/count';
};

export type GetUnreadAlertsCountErrors = {
  /**
   * Bad Request
   */
  400: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Unauthorized
   */
  401: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Forbidden
   */
  403: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Not Found
   */
  404: {
    success: boolean;
    message: string;
    code?: number;
  };
  /**
   * Internal Server Error
   */
  500: {
    success: boolean;
    message: string;
    code?: number;
  };
};

export type GetUnreadAlertsCountError =
  GetUnreadAlertsCountErrors[keyof GetUnreadAlertsCountErrors];

export type GetUnreadAlertsCountResponses = {
  /**
   * Unread alerts count retrieved successfully
   */
  200: {
    success: boolean;
    data: number;
    message: string;
    code?: number;
  };
};

export type GetUnreadAlertsCountResponse =
  GetUnreadAlertsCountResponses[keyof GetUnreadAlertsCountResponses];
